cd ../Activity && git remote set-url origin --add --push  https://github.com/aurmich/module_activity_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_activity_fila3.git
cd ../Blog && git remote set-url origin --add --push  https://github.com/aurmich/module_blog_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_blog_fila3.git
cd ../Cms && git remote set-url origin --add --push  https://github.com/aurmich/module_cms_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_cms_fila3.git
cd ../Gdpr && git remote set-url origin --add --push  https://github.com/aurmich/module_gdpr_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_gdpr_fila3.git
cd ../Geo && git remote set-url origin --add --push  https://github.com/aurmich/module_geo_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_geo_fila3.git
cd ../Job && git remote set-url origin --add --push  https://github.com/aurmich/module_job_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_job_fila3.git
cd ../Lang && git remote set-url origin --add --push  https://github.com/aurmich/module_lang_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_lang_fila3.git
cd ../Media && git remote set-url origin --add --push  https://github.com/aurmich/module_media_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_media_fila3.git
cd ../Notify && git remote set-url origin --add --push  https://github.com/aurmich/module_notify_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_notify_fila3.git
cd ../Rating && git remote set-url origin --add --push  https://github.com/aurmich/module_rating_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_rating_fila3.git
cd ../Seo && git remote set-url origin --add --push  https://github.com/aurmich/module_seo_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_seo_fila3.git
cd ../Setting && git remote set-url origin --add --push  https://github.com/aurmich/module_setting_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_setting_fila3.git
cd ../Tenant && git remote set-url origin --add --push  https://github.com/aurmich/module_tenant_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_tenant_fila3.git
cd ../Ticket && git remote set-url origin --add --push  https://github.com/aurmich/module_ticket_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_ticket_fila3.git
cd ../UI && git remote set-url origin --add --push  https://github.com/aurmich/module_ui_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_ui_fila3.git
cd ../User && git remote set-url origin --add --push  https://github.com/aurmich/module_user_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_user_fila3.git
cd ../Xot && git remote set-url origin --add --push  https://github.com/aurmich/module_xot_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/module_xot_fila3.git
#--
cd ../../Themes/Sixteen && git remote set-url origin --add --push  https://github.com/aurmich/theme_sixteen_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/theme_sixteen_fila3.git
cd ../../Themes/TwentyOne && git remote set-url origin --add --push  https://github.com/aurmich/theme_twentyone_fila3.git && git remote set-url origin --add --push  https://github.com/laraxot/theme_twentyone_fila3.git
